export default [
  { code: 'moscow', title: 'Москва', rid: 1, cid: 20, order: 0 },
  { code: 'moscow-region', title: 'Московская обл.', rid: 2, cid: 20 },
  { code: 'saint-petersburg', title: 'Санкт-Петербург', rid: 3, cid: 20, order: 1 },
  { code: 'leningrad-region', title: 'Ленинградская обл.', rid: 37, cid: 20 },
  { code: 'tula-region', title: 'Тульская обл.', rid: 16, cid: 20 },
  { code: 'rostov-region', title: 'Ростовская обл.', rid: 55, cid: 20 },
  { code: 'kemerovo-region', title: 'Кемеровская обл.', rid: 21, cid: 20 },
  { code: 'lipetsk-region', title: 'Липецкая обл.', rid: 12, cid: 20 },
  { code: 'krasnodar-territory', title: 'Краснодарский край', rid: 19, cid: 20 },
  { code: 'sakhalin-region', title: 'Сахалинская обл.', rid: 59, cid: 20 },
  { code: 'volgograd-region', title: 'Волгоградская обл.', rid: 52, cid: 20 },
  { code: 'chechen-republic', title: 'Чеченская Республика', rid: 50, cid: 20 },
  { code: 'republic-of-daghestan', title: 'Республика Дагестан', rid: 58, cid: 20 },

  { code: 'ru', title: 'Россия', rid: 0, cid: 20 },
  { code: 'us', title: 'США', rid: 0, cid: 23 },
  { code: 'cn', title: 'Китай', rid: 0, cid: 4 },
  { code: 'it', title: 'Италия', rid: 0, cid: 13 },
  { code: 'de', title: 'Германия', rid: 0, cid: 29 },
  { code: 'gb', title: 'Великобритания', rid: 0, cid: 21 },
  { code: 'ua', title: 'Украина', rid: 0, cid: 112 },
  { code: 'by', title: 'Беларусь', rid: 0, cid: 113 },
  { code: 'lt', title: 'Литва', rid: 0, cid: 144 },
  { code: 'lv', title: 'Латвия', rid: 0, cid: 111 }
]
