export default [
  { code: 'moscow', title: 'Москва', rid: 1, cid: 20, order: 0 },
  { code: 'moscow-region', title: 'Московская обл.', rid: 2, cid: 20 },
  { code: 'saint-petersburg', title: 'Санкт-Петербург', rid: 3, cid: 20, order: 1 },
  { code: 'leningrad-region', title: 'Ленинградская обл.', rid: 37, cid: 20 },
  { code: 'tula-region', title: 'Тульская обл.', rid: 16, cid: 20 },
  { code: 'rostov-region', title: 'Ростовская обл.', rid: 55, cid: 20 },
  { code: 'kemerovo-region', title: 'Кемеровская обл.', rid: 21, cid: 20 },
  { code: 'lipetsk-region', title: 'Липецкая обл.', rid: 12, cid: 20 },
  { code: 'krasnodar-territory', title: 'Краснодарский край', rid: 19, cid: 20 },
  { code: 'sakhalin-region', title: 'Сахалинская обл.', rid: 59, cid: 20 },
  { code: 'volgograd-region', title: 'Волгоградская обл.', rid: 52, cid: 20 },
  { code: 'chechen-republic', title: 'Чеченская Республика', rid: 50, cid: 20 },
  { code: 'republic-of-daghestan', title: 'Республика Дагестан', rid: 58, cid: 20 },

  { code: 'ru', title: 'Россия', rid: 0, cid: 20 },
  { code: 'us', title: 'США', rid: 0, cid: 23 },
  { code: 'cn', title: 'Китай', rid: 0, cid: 4 },
  { code: 'it', title: 'Италия', rid: 0, cid: 13 },
  { code: 'de', title: 'Германия', rid: 0, cid: 29 },
  { code: 'gb', title: 'Великобритания', rid: 0, cid: 21 },
  { code: 'ua', title: 'Украина', rid: 0, cid: 112 },
  { code: 'by', title: 'Беларусь', rid: 0, cid: 113 },
  { code: 'lt', title: 'Литва', rid: 0, cid: 144 },
  { code: 'lv', title: 'Латвия', rid: 0, cid: 111 },
  { code: 'md', title: 'Молдова', rid: 0, cid: 138 },

  { code: 'am', title: 'Армения', rid: 0, cid: 126 },
  { code: 'kz', title: 'Казахстан', rid: 0, cid: 16 },
  { code: 'uz', title: 'Узбекистан', rid: 0, cid: 152 },
  { code: 'kg', title: 'Кыргызстан', rid: 0, cid: 210 },
  { code: 'fr', title: 'Франция', rid: 0, cid: 12 },
  { code: 'ir', title: 'Иран', rid: 0, cid: 30 },
  { code: 'tr', title: 'Турция', rid: 0, cid: 109 },
  { code: 'be', title: 'Бельгия', rid: 0, cid: 56 },
  { code: 'nl', title: 'Нидерланды', rid: 0, cid: 33 },
  { code: 'br', title: 'Бразилия', rid: 0, cid: 58 },
  { code: 'ca', title: 'Канада', rid: 0, cid: 24 },
  { code: 'ch', title: 'Швейцария', rid: 0, cid: 59 },
  { code: 'pt', title: 'Португалия', rid: 0, cid: 17 },
  { code: 'at', title: 'Австрия', rid: 0, cid: 127 },
  { code: 'in', title: 'Индия', rid: 0, cid: 6 },
  { code: 'pl', title: 'Польша', rid: 0, cid: 110 },
  { code: 'cz', title: 'Чехия', rid: 0, cid: 114 },
  { code: 'il', title: 'Израиль', rid: 0, cid: 34 }
]
